name: Deploy to Azure Static Web App

on:
  push:
    branches:
      - main  # Du kan ändra till den gren du använder för din produktion

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Azure CLI
    - name: Set up Azure CLI
      uses: azure/setup-azurecli@v1

    # Logga in med GitHub personal access token
    - name: Set up GitHub token
      run: |
        echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

    # Logga in på Azure
    - name: Login to Azure
      run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

    # Installera SWA CLI
    - name: Install SWA CLI
      run: |
        npm install -g @azure/static-web-apps-cli

    # Bygg din React app
    - name: Build React app
      run: |
        npm install
        npm run build

    # Deploy till Azure Static Web App
    - name: Deploy to Azure Static Web App
      run: |
        swa deploy ./dist --app-name ${{ secrets.AZURE_APP_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --token ${{ secrets.GITHUB_TOKEN }} --region swedencentral
