name: Deploy to Azure Static Web App

on:
  push:
    branches:
      - main  # Ändra till din produktionsgren om nödvändigt

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3  # Uppdaterad till v3

    # 2️⃣ Logga in på Azure med service principal
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    # 3️⃣ Installera SWA CLI globalt
    - name: Install SWA CLI
      run: npm install -g @azure/static-web-apps-cli

    # 4️⃣ Bygg din React-app
    - name: Build React app
      run: |
        npm install
        npm run build

    # 5️⃣ Deploy till Azure Static Web Apps
    - name: Deploy to Azure Static Web App
      run: |
        swa deploy ./dist \
          --app-name ${{ secrets.AZURE_APP_NAME }} \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --token ${{ secrets.AZURE_DEPLOYMENT_TOKEN }} \
          --verbose
